# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-10 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180110_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
